# Task
Create a Python notebook that uses NumPy to manage student marks data. The notebook should demonstrate data creation, exploration, transformation, combination, modification, data type handling, and the difference between array copies and views.

## Data creation

### Subtask:
Create NumPy arrays for students, subjects, and their marks.


**Reasoning**:
Create numpy arrays for students, subjects, and marks as instructed.



In [8]:
import numpy as np

students = np.array(['Alice', 'Bob', 'Charlie', 'David', 'Eve'])
subjects = np.array(['Math', 'Science', 'English', 'History'])
marks = np.array([[85, 90, 78, 92],
                  [70, 88, 95, 80],
                  [92, 75, 82, 88],
                  [65, 70, 75, 72],
                  [98, 91, 89, 94]], dtype=int)

print("Students:", students)
print("Subjects:", subjects)
print("Marks:\n", marks)

Students: ['Alice' 'Bob' 'Charlie' 'David' 'Eve']
Subjects: ['Math' 'Science' 'English' 'History']
Marks:
 [[85 90 78 92]
 [70 88 95 80]
 [92 75 82 88]
 [65 70 75 72]
 [98 91 89 94]]


## Data exploration

### Subtask:
Examine the shape, size, and dimensions of the created arrays.


**Reasoning**:
Print the shape, size, and dimensions of the created arrays as requested by the instructions.



In [9]:
print("Shape of students array:", students.shape)
print("Size of students array:", students.size)
print("Dimensions of students array:", students.ndim)

print("\nShape of subjects array:", subjects.shape)
print("Size of subjects array:", subjects.size)
print("Dimensions of subjects array:", subjects.ndim)

print("\nShape of marks array:", marks.shape)
print("Size of marks array:", marks.size)
print("Dimensions of marks array:", marks.ndim)

Shape of students array: (5,)
Size of students array: 5
Dimensions of students array: 1

Shape of subjects array: (4,)
Size of subjects array: 4
Dimensions of subjects array: 1

Shape of marks array: (5, 4)
Size of marks array: 20
Dimensions of marks array: 2


## Data transformation

### Subtask:
Reshape and reorganize the marks array to demonstrate different views of the data.


**Reasoning**:
Reshape the marks array into a 1D array, a new 2D array with subjects as rows and students as columns, and create a view of the first two rows of the original marks array, and print the shape and the arrays/views.



In [10]:
marks_flat = marks.reshape(-1)
print("Reshaped marks (1D):")
print("Shape:", marks_flat.shape)
print(marks_flat)

marks_transposed = marks.T
print("\nReshaped marks (subjects as rows, students as columns):")
print("Shape:", marks_transposed.shape)
print(marks_transposed)

marks_view = marks[:2, :]
print("\nView of the first two rows of original marks array:")
print("Shape:", marks_view.shape)
print(marks_view)

Reshaped marks (1D):
Shape: (20,)
[85 90 78 92 70 88 95 80 92 75 82 88 65 70 75 72 98 91 89 94]

Reshaped marks (subjects as rows, students as columns):
Shape: (4, 5)
[[85 70 92 65 98]
 [90 88 75 70 91]
 [78 95 82 75 89]
 [92 80 88 72 94]]

View of the first two rows of original marks array:
Shape: (2, 4)
[[85 90 78 92]
 [70 88 95 80]]


## Data combination

### Subtask:
Combine or split arrays to simulate adding/removing students or subjects.


**Reasoning**:
Create new arrays for a new student and an extra subject, then use `np.vstack` and `np.hstack` to combine them with the existing marks array as per the instructions.



In [11]:
new_student_marks = np.array([[88, 92, 85, 90]])
combined_marks_student = np.vstack((marks, new_student_marks))
print("Combined marks after adding a new student:")
print("Shape:", combined_marks_student.shape)
print(combined_marks_student)

extra_subject_marks = np.array([[80], [85], [78], [90], [95]])
combined_marks_subject = np.hstack((marks, extra_subject_marks))
print("\nCombined marks after adding a new subject:")
print("Shape:", combined_marks_subject.shape)
print(combined_marks_subject)

Combined marks after adding a new student:
Shape: (6, 4)
[[85 90 78 92]
 [70 88 95 80]
 [92 75 82 88]
 [65 70 75 72]
 [98 91 89 94]
 [88 92 85 90]]

Combined marks after adding a new subject:
Shape: (5, 5)
[[85 90 78 92 80]
 [70 88 95 80 85]
 [92 75 82 88 78]
 [65 70 75 72 90]
 [98 91 89 94 95]]


## Data modification

### Subtask:
Modify array elements to update marks, and demonstrate unique values.


**Reasoning**:
Select and modify a specific element and a slice of the marks array, then find the unique marks.



In [12]:
# 1. Select a specific element and change its value (e.g., Alice's Science mark)
marks[0, 1] = 92
print("Marks after updating Alice's Science mark:")
print(marks)

# 2. Select a slice and modify multiple elements (e.g., Charlie's marks)
marks[2, :] = [95, 80, 88, 91]
print("\nMarks after updating Charlie's marks:")
print(marks)

# 3. Use np.unique to find and print unique marks
unique_marks = np.unique(marks)
print("\nUnique marks in the array:")
print(unique_marks)

Marks after updating Alice's Science mark:
[[85 92 78 92]
 [70 88 95 80]
 [92 75 82 88]
 [65 70 75 72]
 [98 91 89 94]]

Marks after updating Charlie's marks:
[[85 92 78 92]
 [70 88 95 80]
 [95 80 88 91]
 [65 70 75 72]
 [98 91 89 94]]

Unique marks in the array:
[65 70 72 75 78 80 85 88 89 91 92 94 95 98]


## Data type handling

### Subtask:
Show how data types can be changed and the impact on operations.


**Reasoning**:
Print the current data type of the marks array, convert it to float, print the new data type, and perform division on both to show the impact.



In [13]:
# 1. Print the current data type of the marks array
print("Original data type of marks:", marks.dtype)

# 2. Convert the marks array to a floating-point data type
marks_float = marks.astype(np.float64)

# 3. Print the data type of the new marks_float array
print("New data type of marks_float:", marks_float.dtype)

# 4. Attempt a division operation on the original marks array
marks_divided_int = marks / 2
print("\nDivision result on original integer marks:")
print(marks_divided_int)
print("Data type of division result on original marks:", marks_divided_int.dtype)

# 5. Attempt the same division operation on the marks_float array
marks_divided_float = marks_float / 2
print("\nDivision result on floating-point marks:")
print(marks_divided_float)
print("Data type of division result on floating-point marks:", marks_divided_float.dtype)

Original data type of marks: int64
New data type of marks_float: float64

Division result on original integer marks:
[[42.5 46.  39.  46. ]
 [35.  44.  47.5 40. ]
 [47.5 40.  44.  45.5]
 [32.5 35.  37.5 36. ]
 [49.  45.5 44.5 47. ]]
Data type of division result on original marks: float64

Division result on floating-point marks:
[[42.5 46.  39.  46. ]
 [35.  44.  47.5 40. ]
 [47.5 40.  44.  45.5]
 [32.5 35.  37.5 36. ]
 [49.  45.5 44.5 47. ]]
Data type of division result on floating-point marks: float64


## Copy and view behavior

### Subtask:
Illustrate the difference between array copies and views.


**Reasoning**:
The subtask requires demonstrating the difference between array copies and views by creating a copy and a view of the `marks` array, modifying elements in each, and observing the effect on the original array. I will perform all steps in a single code block.



In [14]:
# 1. Create a new array marks_copy that is a copy of the original marks array
marks_copy = marks.copy()
print("Original marks array:\n", marks)
print("\nCopy of marks array (marks_copy):\n", marks_copy)

# 2. Create a new array marks_view_slice that is a view of a slice of the original marks array
marks_view_slice = marks[:3, :2]
print("\nView of a slice of marks array (marks_view_slice - first 3 rows, first 2 columns):\n", marks_view_slice)

# 3. Modify an element in the marks_copy array
print("\nModifying element [0, 0] in marks_copy...")
marks_copy[0, 0] = 100
print("Modified marks_copy:\n", marks_copy)
print("Original marks after modifying marks_copy:\n", marks) # Show original is not affected

# 4. Modify an element in the marks_view_slice array
print("\nModifying element [0, 0] in marks_view_slice...")
marks_view_slice[0, 0] = 50
print("Modified marks_view_slice:\n", marks_view_slice)
print("Original marks after modifying marks_view_slice:\n", marks) # Show original IS affected

Original marks array:
 [[85 92 78 92]
 [70 88 95 80]
 [95 80 88 91]
 [65 70 75 72]
 [98 91 89 94]]

Copy of marks array (marks_copy):
 [[85 92 78 92]
 [70 88 95 80]
 [95 80 88 91]
 [65 70 75 72]
 [98 91 89 94]]

View of a slice of marks array (marks_view_slice - first 3 rows, first 2 columns):
 [[85 92]
 [70 88]
 [95 80]]

Modifying element [0, 0] in marks_copy...
Modified marks_copy:
 [[100  92  78  92]
 [ 70  88  95  80]
 [ 95  80  88  91]
 [ 65  70  75  72]
 [ 98  91  89  94]]
Original marks after modifying marks_copy:
 [[85 92 78 92]
 [70 88 95 80]
 [95 80 88 91]
 [65 70 75 72]
 [98 91 89 94]]

Modifying element [0, 0] in marks_view_slice...
Modified marks_view_slice:
 [[50 92]
 [70 88]
 [95 80]]
Original marks after modifying marks_view_slice:
 [[50 92 78 92]
 [70 88 95 80]
 [95 80 88 91]
 [65 70 75 72]
 [98 91 89 94]]


## Summary:

### Data Analysis Key Findings

*   The `students` array is a 1D array of size 5, `subjects` is a 1D array of size 4, and `marks` is a 2D array with a shape of (5, 4) and a size of 20.
*   The `marks` array can be reshaped into a 1D array of shape (20,) or transposed into a 2D array of shape (4, 5). A slice of the `marks` array, like the first two rows, creates a view with a shape of (2, 4).
*   New student marks can be added using `np.vstack`, changing the marks array shape from (5, 4) to (6, 4). New subject marks can be added using `np.hstack`, changing the shape from (5, 4) to (5, 5).
*   Individual elements or slices of the `marks` array can be modified directly using indexing and slicing. The `np.unique()` function successfully identified the unique mark values in the array.
*   The original `marks` array had an integer data type (`int64`). It was successfully converted to a floating-point type (`float64`) using `.astype()`. Division on the integer array resulted in a floating-point array, demonstrating NumPy's automatic data type upcasting during operations.
*   Modifying a copy of the `marks` array (created with `.copy()`) does not affect the original array. Modifying a view of the `marks` array (created with slicing) *does* affect the original array, illustrating that views share the same underlying data.

### Insights or Next Steps

*   Understanding the difference between copies and views is crucial in NumPy to avoid unintended modifications of data.
*   NumPy's data type handling and automatic upcasting simplify operations involving different numerical types.
